# Site settings
title: regine erika
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A Blogfolio
baseurl:  # the subpath of your site, e.g. /blog/
url: https://regineerika.github.io # the base hostname & protocol for your site
github_username:  regineerika
instagram_username: regine_erika

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 1
paginate_path: "/blog/page:num/"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  photoportfolio:
    output: true
    permalink: /:photoportfolio/:path/



